#项目启动端口
server:
  port: 8372

#健康监控相关配置
management:
  endpoint:
    health:
      show-details: when_authorized

#项目名字
spring:
  application:
    name: eureka-producer
  #登录注册eureka的用户名以及密码
  security:
    user:
      name: admin
      password: admin123

#eureka相关配置
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8371/eureka/
    registry-fetch-interval-seconds: 5